cacheFolder: .yarn/cache

enableImmutableInstalls: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  vue-loader@*:
    peerDependencies:
      webpack: "*"

pnpMode: loose
