version: '3.8'

services:
  app:
    build: .
    container_name: kynderway_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
    command: php artisan serve --host=0.0.0.0 --port=8000

  queue:
    build: .
    container_name: kynderway_queue
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
    command: php artisan queue:work

  db:
    image: mysql:8.0
    container_name: kynderway_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kynderway
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: kynderway
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  prometheus:
    image: prom/prometheus:latest
    container_name: kynderway_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: kynderway_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  dbdata:
  grafana_data:
