version: '3.8'

services:
  app:
    build: .
    container_name: kynderway_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
    command: php artisan serve --host=0.0.0.0 --port=8000

  queue:
    build: .
    container_name: kynderway_queue
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
    command: php artisan queue:work

  db:
    image: mysql:8.0
    container_name: kynderway_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kynderway
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: kynderway
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
