global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kynderway-app'
    static_configs:
      - targets: ['app:9090']
    metrics_path: '/metrics'
  - job_name: 'mysql'
    static_configs:
      - targets: ['db:3306']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
