<?php

return [

    'emailOptions' => [
        'adminEmail' => env('ADMIN_EMAIL', 'team@kynderway.com')
    ],

    'currencySymbols' => [
        'GBP' => '&pound;',
        'USD' => '&dollar;',
        'EUR' => '&euro;',
    ],

    'londonpostal' => [
        //1 => 'E - East',
        //2 => 'N - North',
        3 => 'W - West',
        //4 => 'S- South',
        5 => 'NW - North West',
        6 => 'SW - South West',
        //7 => 'SE - South East',
        //8 => 'NE - North East',
        9 => 'C - Central',
        //10 => 'EC - East Central',
        11 => 'WC - West Central'
    ],

   'londoncity' => [
        /*
        1 => 'Aberdeen',
        2 => 'Armagh',
        3 => 'Bangor',
        4 => 'Bath',
        5 => 'Belfast',
        6 => 'Birmingham',
        7 => 'Bradford',
        8 => 'Brighton & Hove',
        9 => 'Bristol',
        10 => 'Cambridge',
        11 => 'Canterbury',
        12 => 'Cardiff',
        13 => 'Carlisle',
        14 => 'Chelmsford',
        75 => 'Cheltenham',
        15 => 'Chester',
        16 => 'Chichester',
        17 => 'Coventry',
        71 => 'Cirencester',
        18 => 'Derby',
        19 => 'Derry',
        20 => 'Dundee',
        21 => 'Durham',
        22 => 'Edinburgh',
        23 => 'Ely',
        24 => 'Exeter',
        25 => 'Glasgow',
        26 => 'Gloucester',
        27 => 'Hereford',
        28 => 'Inverness',
        29 => 'Kingston upon Hull',
        30 => 'Lancaster',
        31 => 'Leeds',
        32 => 'Leicester',
        33 => 'Lichfield',
        34 => 'Lincoln',
        35 => 'Lisburn',
        36 => 'Liverpool',
        */
        37 => 'London',
        /*
        38 => 'Manchester',
        74 => 'Marlborough',
        39 => 'Newcastle upon Tyne',
        40 => 'Newport',
        41 => 'Newry',
        42 => 'Norwich',
        43 => 'Nottingham',
        44 => 'Oxford',
        45 => 'Perth',
        46 => 'Peterborough',
        47 => 'Plymouth',
        48 => 'Portsmouth',
        49 => 'Preston',
        50 => 'Ripon',
        51 => 'St Albans',
        52 => 'St Asaph',
        53 => 'St Davids',
        54 => 'Salford',
        55 => 'Salisbury',
        56 => 'Sheffield',
        57 => 'Southampton',
        72 => 'Stroud',
        58 => 'Stirling',
        59 => 'Stoke-on-Trent',
        60 => 'Sunderland',
        61 => 'Swansea',
        70 => 'Swindon',
        62 => 'Truro',
        73 => 'Tetbury',
        63 => 'Wakefield',
        64 => 'Wells',
        65 => 'City of Westminster',
        66 => 'Winchester',
        67 => 'Wolverhampton',
        68 => 'Worcester',
        69 => 'York'
        */
    ],

    'language_supported' => [
        "Albanian",
        "Algerian Arabic",
        "Amharic",
        "Assamese",
        "Bavarian",
        "Bengali",
        "Bhojpuri",
        "Bosnian",
        "Bulgarian",
        "Burmese",
        "Cantonese",
        "Catalan",
        "Cebuano",
        "Chhattisgarhi",
        "Chittagonian",
        "Croatian",
        "Czech",
        "Danish",
        "Dari",
        "Deccan",
        "Dutch",
        "Eastern Punjabi",
        "Egyptian Arabic",
        "English",
        "Estonian",
        "Farsi",
        "Filipino",
        "Finnish",
        "French",
        "Gan Chinese",
        "Georgian",
        "German (only Standard German)",
        "Greek",
        "Gujarati",
        "Hakka Chinese",
        "Hausa",
        "Hebrew",
        "Hejazi Arabic",
        "Hindi (sanskritised Hindustani)",
        "Hungarian",
        "Icelandic",
        "Igbo",
        "Indonesian",
        "Indonesian (Indonesian Malay)",
        "Iranian Persian",
        "Italian",
        "Japanese",
        "Javanese",
        "Jin Chinese",
        "Kannada",
        "Kazakh",
        "Khmer",
        "Kinyarwanda",
        "Korean",
        "Lao",
        "Latvian",
        "Lithuanian",
        "Macedonian",
        "Magahi",
        "Maithili",
        "Malayalam",
        "Malaysian (Malaysian Malay)",
        "Mandarin Chinese",
        "Marathi",
        "Mesopotamian Arabic",
        "Min Bei Chinese",
        "Min Dong Chinese",
        "Min Nan Chinese",
        "Moroccan Arabic",
        "Nepali",
        "Nigerian Fulfulde",
        "North Levantine Arabic",
        "Northern Kurdish",
        "Northern Pashto",
        "Northern Uzbek",
        "Norwegian",
        "Odia",
        "Polish",
        "Portuguese",
        "Romanian",
        "Rundi",
        "Russian",
        "Sanaani Spoken Arabic",
        "Saraiki",
        "Saʽidi Arabic",
        "Serbian",
        "Sindhi",
        "Sinhalese",
        "Slovakian",
        "Slovene",
        "Somali",
        "South Azerbaijani",
        "South Levantine Arabic",
        "Southern Pashto",
        "Spanish",
        "Sudanese Arabic",
        "Sunda",
        "Sylheti",
        "Tagalog",
        "Tamil",
        "Taʽizzi-Adeni Arabic",
        "Telugu",
        "Thai",
        "Tunisian Arabic",
        "Turkish",
        "Ukrainian",
        "Urdu (persianised Hindustani)",
        "Uyghur",
        "Vietnamese",
        "Western Punjabi",
        "Wu Chinese",
        "Xiang Chinese",
        "Yoruba",
        "Yue Chinese",
        "Zulu",
    ],
];
