name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [8.1, 8.2]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: kynderway
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_USER: kynderway
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -psecret"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: kynderway
          DB_USERNAME: kynderway
          DB_PASSWORD: password
        run: php artisan migrate --force
      - name: Run PHP CS Fixer
        run: composer lint
      - name: Run Larastan
        run: composer lint:phpstan
      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: kynderway
          DB_USERNAME: kynderway
          DB_PASSWORD: password
        run: php artisan test --testdox
